### ISSUE TITLE
hover feature over the person's name in friendlist page

### ISSUE THREAD

**Issue by Sypher0Dronzer** [ishant9805/FacebookClone#14]
I wish to add a hover addition to the friendlist page where on hovering it will show the persons details like this.
![image](https://github.com/ishant9805/FacebookClone/assets/83546205/b47398a6-be3d-41e8-88cf-58e161cfad06)
 
@ishant9805  Sir,
Please assign this issue to me

**Comment by ishant9805** [comment]
You are assigned, Good Luck🤞
