### ISSUE TITLE
Fix:Card-section

### ISSUE THREAD

**Issue by Abhishek-465** [ishant9805/FacebookClone#16]
Description: The Login card is not alt all responsive.

Steps to reproduce:
1>Open the website.
2>Reduce the screen size to 800px or view it in a tablet or mobile phone.

Screenshot:
![Screenshot (26)](https://github.com/ishant9805/FacebookClone/assets/127030695/0a425882-c7d8-4cbd-b05a-fac791af9158)

I would like to address this issue.

**Comment by Abhishek-465** [comment]
@ishant9805  Kindly look into this issue.

**Comment by ishant9805** [comment]
I have assigned this issue to you kindly solve it for me. @Abhishek-465
