### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by Deepankar1484** [ishant9805/FacebookClone#24]
Hey @ishant9805 , Hope you are doing great. I can help you in updating the README file for the visitors.
please assign the task and make me a hactober fest labeled

**Comment by ishant9805** [comment]
Thanks for your help brother, assigning you!

**Comment by Deepankar1484** [comment]
hey @ishant9805 , please add hacktoberfest label to it

**Comment by ishant9805** [comment]
Everything related to hacktober is already done to the repo. You just need to contribute and the PRs will be counted in your hacktober profile @Deepankar1484.

**Comment by Deepankar1484** [comment]
hello @ishant9805, Hope you are good. I am saying that make the issue labeled for hacktoberfest.
You can make my issue as hacktoberfest-accepted.

**Comment by ishant9805** [comment]
There is no need. The repo should be tagged with hacktoberfest-accepted not the issue brother @Deepankar1484. I have already done this. So just don't worry. It will work.
