### ISSUE TITLE
Dark mode Button is not styled good

### ISSUE THREAD

**Issue by ashfaque-mustaque** [ishant9805/FacebookClone#27]
hey @ishant9805 bro your dark mode button is not looking I wanna to make its style good and also want to add more contribution  to your repo.
assign me brother

**Comment by ashfaque-mustaque** [comment]
@ishant9805 i did this try to merge it soon brother

**Comment by ishant9805** [comment]
Can you share the screenshot?

**Comment by ashfaque-mustaque** [comment]
![Capture23](https://github.com/ishant9805/FacebookClone/assets/106698498/d24d6d00-da87-4798-8ba5-b992bc9afac3)
![Capture23](https://github.com/ishant9805/FacebookClone/assets/106698498/7e2b980a-9376-4193-af39-141aca8d5bf8)

**Comment by ishant9805** [comment]
Will merge your PR

**Comment by ashfaque-mustaque** [comment]
brother please add the label of hacktoberfest please

**Comment by ashfaque-mustaque** [comment]
after adding label please try to merge it soon bcz it will undergo for verification by the hacktoberfest team..

**Comment by ishant9805** [comment]
Bro, it's already a hacktoberfest accepted repo. Hacktoberfest reviews in 7 days then it will update on the website. The issues need not to be tagged, tagging the repo is enough. Other contributors have already contributed and got their badges from hacktoberfest. So, don't worry.

**Comment by ashfaque-mustaque** [comment]
Still showing Not accepted

**Comment by ishant9805** [comment]
It must be showing a counter beside the PR list. If it's showing the timer then it's good. Or you can share a ss, then I will look into the matter.
