### ISSUE TITLE
Creating 'Forgot Password' Page

### ISSUE THREAD

**Issue by HemanthKR07** [ishant9805/FacebookClone#3]

**Comment by ishant9805** [comment]
Should I assign this task to you @HemanthKR07 ? Can you do it?

**Comment by HemanthKR07** [comment]
Yes please, I can fix this.

**Comment by ishant9805** [comment]
You have been assigned.

**Comment by ishant9805** [comment]
whenever you complete it @HemanthKR07, you can also reach out to me on [LinkedIn](https://www.linkedin.com/in/ishantkumar9805)

**Comment by HemanthKR07** [comment]
Hey @ishant9805, 
Have created a PR, please review it and merge.

**Comment by ishant9805** [comment]
Hey @HemanthKR07, I have mereged your PR can you please make the nav bar similar to facebook as this is a clone to facebook. And also rename the title to Forgotten Password.
