### ISSUE TITLE
 Favicon is missing

### ISSUE THREAD

**Issue by AnkitShahu** [ishant9805/FacebookClone#4]
favicon is missing 
![image](https://github.com/ishant9805/FacebookClone/assets/57070667/8027a66a-8ace-4e45-bc8f-0343fc22c92f)

**Comment by AnkitShahu** [comment]
Can I fix this issue?

**Comment by ishant9805** [comment]
Yup, why not? I am assigning you to solve. When you complete it just open a pull request if you need any help ping me on [linkedin](https://www.linkedin.com/in/ishantkumar9805)

**Comment by ishant9805** [comment]
Hello Sir(@AnkitShahu ), can you please add the favicon also in forgot password page and also link both pages back and forth.

**Comment by AnkitShahu** [comment]
ok sure

**Comment by ishant9805** [comment]
Thanks a lot @AnkitShahu
